### ISSUE TITLE
Add support for Kubernetes endpoints

### ISSUE THREAD

**Issue by moltar** [johnbwoodruff/digitalocean-js#15]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi John! Is Kubernetes support planned? Thanks.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://developers.digitalocean.com/documentation/v2/#kubernetes

**Comment by johnbwoodruff** [comment]
Sorry I haven't gotten back to you yet @moltar it's been a crazy few months with me changing jobs. I hope to work on this soon and get all currently existing APIs supported, including Kubernetes. As soon as I've got something to share, I'll update here.

**Comment by johnbwoodruff** [comment]
@moltar well it took WAY too long coming, but I just published a new version with kubernetes support.
