### ISSUE TITLE
purgeEndpointCache calls wrong Endpoint

### ISSUE THREAD

**Issue by felix-voicehub** [johnbwoodruff/digitalocean-js#23]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
`purgeEndpointCache` issues a `DELETE` on the following endpoint: `${environment_1.API_BASE_URL}/cdn/endpoints/${id}`.

**This actually deletes that CDN endpoint**. There needs to be a `/cache` at the end, see https://developers.digitalocean.com/documentation/v2/#purge-the-cache-for-an-existing-cdn-endpoint.

**Comment by johnbwoodruff** [comment]
Released in [v1.5.2](https://github.com/johnbwoodruff/digitalocean-js/releases/tag/v1.5.2)
