### ISSUE TITLE
Create Droplet from snapshot

### ISSUE THREAD

**Issue by jesusbibieca** [johnbwoodruff/digitalocean-js#29]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**
Hello!
First, I'd like to say great work here, this is really amazing.

I'm new around here and I'm not sure if this is possible or not already in this project and probably I just have not seen it.

I'd like to be able to create a droplet from a snapshot [reference](https://www.digitalocean.com/docs/images/snapshots/quickstart/#create-droplets-and-volumes-from-snapshots)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by johnbwoodruff** [comment]
It is indeed possible! :) You can use the [createNewDroplet](https://johnbwoodruff.github.io/digitalocean-js/classes/dropletservice.html#createnewdroplet) method and pass your snapshot id in the `image` parameter. This will create a new droplet from your snapshot.

**Comment by jesusbibieca** [comment]
Great!!! Thank you

**Comment by johnbwoodruff** [comment]
Hopefully you find digitalocean-js helpful to you! :) And as always, open an issue if you run into any other problems!
