### ISSUE TITLE
Should use Axios instance instead of setting global config

### ISSUE THREAD

**Issue by LubomirGeorgiev** [johnbwoodruff/digitalocean-js#30]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
This library pollutes the global/common Axios config with it's own config and then if you want to use Axios in your own project the config from this library gets inherited. What I am talking about is [this](https://github.com/johnbwoodruff/digitalocean-js/blob/a75321b27f32a076fb85e7d35b3daf0d38c1c90f/src/lib/digitalocean.ts#L53-L55). My problem is that I am downloading data from an S3 Bucket and the `Authorization` header that you add gets sent to S3 which returns and 400 error because of it. Also I don't want to inherit any of the axios configuration that this library uses.

# Solution
Axios has a special function for this use case called `axios.create` which will create a new reusable instance where you can put your own headers/configs and stuff.

**Comment by johnbwoodruff** [comment]
Fixed and released to npm as v1.5.6. Thanks for reporting @LubomirGeorgiev!

**Comment by LubomirGeorgiev** [comment]
> Fixed and released to npm as v1.5.6. Thanks for reporting @LubomirGeorgiev!

Wow that was fast :D

**Comment by johnbwoodruff** [comment]
Well formatted issue with a proposed solution that was well thought through! 😄 Easy to do! Thanks again for the suggestion!
