### ISSUE TITLE
Types lost in v2.1.0

### ISSUE THREAD

**Issue by rhythmbhiwani** [johnbwoodruff/digitalocean-js#69]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
On [npm.js](https://www.npmjs.com/package/digitalocean-js), since v2.1.0, the typescript icon has disappered, and also the IDE has started to throw error that it's types are not found. Please fix it

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by johnbwoodruff** [comment]
Hey @rhythmbhiwani I'm not sure how I completely missed this issue creation! Turns out I messed up my publishing of 2.1.0, I've fixed it and published `2.1.2` and it's now working properly again. Thanks so much for the issue, and sorry again for the massive delay in seeing it!
